### ISSUE TITLE
lsp-common.el has been removed from lsp

### ISSUE THREAD

**Issue by tarsius** [MagB93/lsp-fortran#2]
https://github.com/emacs-lsp/lsp-mode/commit/439df1e463b3778cea5ddcdb2fccbf27b6a9fb5f

**Comment by MagBad** [comment]
Thank's for submitting the issue. I'm currently working on the small details of the new API
that's required by lsp-mode. Feel free to join at [lsp-mode gitter](https://gitter.im/emacs-lsp/lsp-mode)!

As a workaround I recomment using [eglot](https://github.com/joaotavora/eglot), also refer to 669f5bc7480bd0b931d9b58f35299b2b17a2a860.

**Comment by tarsius** [comment]
Thanks!

Also for the hint, it might help others. I don't actually use this package; I just ran into this as part of my work on the Emacsmirror.

**Comment by MagBad** [comment]
Due to [Support for the Fortran-language-server](https://github.com/emacs-lsp/lsp-mode/commit/2c1755d76387bed7c96a9c827753b6dcd9cf1a2c) this package is going to be deprecated soon. I'll update the README.md soon. 
This case this thereby closed.
